include:
- remote: https://devops-pipeline-manager-production.{DOMAIN}.ru/manifest.yml?sources=/ci/global/stages&.yml
- remote: https://devops-pipeline-manager-production.{DOMAIN}.ru/manifest.yml?sources=/ci/jobs/build/kaniko&.yml
- remote: https://devops-pipeline-manager-production.{DOMAIN}.ru/manifest.yml?sources=/ci/jobs/utils/with-submodules&.yml
- remote: https://devops-pipeline-manager-production.{DOMAIN}.ru/manifest.yml?sources=/ci/workflow/review-on-mr&.yml
- remote: https://devops-pipeline-manager-production.{DOMAIN}.ru/manifest.yml?sources=/ci/jobs/deploy/argocd-staging&.yml
variables:
#  DEPLOYMENT_LOAD_ENV_SECRETS: token
  DEPLOY_FROM: .k8s
  HTTP_PORT: '8011'
  HTTP_SUBDOMAIN_ON: ".HTTP_SUBDOMAIN_ON.ru"
#  MINIO_ENABLED: v2
  POSTGRES_ENABLED: 'true'
  #  REDIS_ENABLED: "true"
argocd:
  variables:
    S_APP_LOG_LEVEL: 'INFO'
    S_APP_ENVIRONMENT_TYPE: 'prod'
    S_POSTHOG_HOST: 'https://hog.trendsurfers.ru'
argocd staging:
  variables:
    S_APP_LOG_LEVEL: 'DEBUG'
    S_APP_ENVIRONMENT_TYPE: 'dev'
    S_POSTHOG_HOST: 'https://hog.trendsurfers.ru'
