services:

  postgres:
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TEMPLATE_POSTGRES_NAME"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "5434:5432"
    networks:
      - traefik-proxy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  redis:
    ports:
      - "6379:6379"
    networks:
      - traefik-proxy
    volumes:
      - redis_data:/data
    command: ["redis-server", "--maxmemory-policy", "volatile-lru"]
networks:
  traefik-proxy:
    name: traefik-proxy
    external: true
