services:

  postgres:
    image: postgres:latest
    container_name: TEMPLATE_POSTGRES_NAME

  redis:
    image: redis:latest
    container_name: TEMPLATE_REDIS_NAME

volumes:
  postgres_data:
  redis_data:
