services:

  postgres:
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "5434:5432"
    networks:
      - traefik-proxy
    volumes:
      - postgres_data:/data

  redis:
    ports:
      - "6379:6379"
    networks:
      - traefik-proxy
    volumes:
      - redis_data:/data
    command: ["redis-server", "--maxmemory-policy", "volatile-lru"]

  minio:
    env_file:
      - .env
    ports:
      - "9000:9000"  # API port
      - "10000:9001"  # console port
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: unless-stopped

networks:
  traefik-proxy:
    name: traefik-proxy
    external: true
