services:

  db:
    env_file:
      - env/.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d DB_NAME"]  # TODO DB_NAME replace
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "5434:5432"
    networks:
      - traefik-proxy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

#  redis:
#    ports:
#      - "6379:6379"
#    networks:
#      - traefik-proxy
#    volumes:
#      - redis_data:/data

networks:
  traefik-proxy:
    name: traefik-proxy
    external: true
